use_frameworks!

target 'ObjectMapper Sample' do
  pod 'APIKitExt/ObjectMapper', :path => '../'
  pod 'APIKitExt/RxSwift', :path => '../'
end

target 'Argo Sample' do
  pod 'APIKitExt/Argo', :path => '../'
  pod 'Curry', '3.0.0'
  pod 'APIKitExt/RxSwift', :path => '../'
end

target 'Himotoki Sample' do
  pod 'APIKitExt/Himotoki', :path => '../'
  pod 'APIKitExt/RxSwift', :path => '../'
  pod 'RxCocoa', '~> 3.0'

  target 'Himotoki Sample Tests' do
    inherit! :search_paths
    pod 'RxTest', '~> 3.0'
  end
end

target 'SwiftyJSON Sample' do
  pod 'APIKitExt/SwiftyJSON', :path => '../'
  pod 'APIKitExt/RxSwift', :path => '../'
end

